/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  User,
} from './models';

export namespace Components {
  interface AppAuth {}
  interface AppAuthGuard {
    'authenticated': (user: User) => any;
    'unauthenticated': () => any;
  }
  interface AppAuthPage {}
  interface AppDropdown {
    'class'?: string;
  }
  interface AppDropdownItem {}
  interface AppHeader {}
  interface AppHome {}
  interface AppHomePage {}
  interface AppRoot {}
}

declare global {


  interface HTMLAppAuthElement extends Components.AppAuth, HTMLStencilElement {}
  var HTMLAppAuthElement: {
    prototype: HTMLAppAuthElement;
    new (): HTMLAppAuthElement;
  };

  interface HTMLAppAuthGuardElement extends Components.AppAuthGuard, HTMLStencilElement {}
  var HTMLAppAuthGuardElement: {
    prototype: HTMLAppAuthGuardElement;
    new (): HTMLAppAuthGuardElement;
  };

  interface HTMLAppAuthPageElement extends Components.AppAuthPage, HTMLStencilElement {}
  var HTMLAppAuthPageElement: {
    prototype: HTMLAppAuthPageElement;
    new (): HTMLAppAuthPageElement;
  };

  interface HTMLAppDropdownElement extends Components.AppDropdown, HTMLStencilElement {}
  var HTMLAppDropdownElement: {
    prototype: HTMLAppDropdownElement;
    new (): HTMLAppDropdownElement;
  };

  interface HTMLAppDropdownItemElement extends Components.AppDropdownItem, HTMLStencilElement {}
  var HTMLAppDropdownItemElement: {
    prototype: HTMLAppDropdownItemElement;
    new (): HTMLAppDropdownItemElement;
  };

  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppHomePageElement extends Components.AppHomePage, HTMLStencilElement {}
  var HTMLAppHomePageElement: {
    prototype: HTMLAppHomePageElement;
    new (): HTMLAppHomePageElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-auth': HTMLAppAuthElement;
    'app-auth-guard': HTMLAppAuthGuardElement;
    'app-auth-page': HTMLAppAuthPageElement;
    'app-dropdown': HTMLAppDropdownElement;
    'app-dropdown-item': HTMLAppDropdownItemElement;
    'app-header': HTMLAppHeaderElement;
    'app-home': HTMLAppHomeElement;
    'app-home-page': HTMLAppHomePageElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface AppAuth {}
  interface AppAuthGuard {
    'authenticated': (user: User) => any;
    'unauthenticated': () => any;
  }
  interface AppAuthPage {}
  interface AppDropdown {
    'class'?: string;
  }
  interface AppDropdownItem {
    'onAppClick'?: (event: CustomEvent<any>) => void;
  }
  interface AppHeader {}
  interface AppHome {}
  interface AppHomePage {}
  interface AppRoot {}

  interface IntrinsicElements {
    'app-auth': AppAuth;
    'app-auth-guard': AppAuthGuard;
    'app-auth-page': AppAuthPage;
    'app-dropdown': AppDropdown;
    'app-dropdown-item': AppDropdownItem;
    'app-header': AppHeader;
    'app-home': AppHome;
    'app-home-page': AppHomePage;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-auth': LocalJSX.AppAuth & JSXBase.HTMLAttributes<HTMLAppAuthElement>;
      'app-auth-guard': LocalJSX.AppAuthGuard & JSXBase.HTMLAttributes<HTMLAppAuthGuardElement>;
      'app-auth-page': LocalJSX.AppAuthPage & JSXBase.HTMLAttributes<HTMLAppAuthPageElement>;
      'app-dropdown': LocalJSX.AppDropdown & JSXBase.HTMLAttributes<HTMLAppDropdownElement>;
      'app-dropdown-item': LocalJSX.AppDropdownItem & JSXBase.HTMLAttributes<HTMLAppDropdownItemElement>;
      'app-header': LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-home-page': LocalJSX.AppHomePage & JSXBase.HTMLAttributes<HTMLAppHomePageElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
    }
  }
}


