/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppAuth {}
  interface AppAuthPage {}
  interface AppHeader {}
  interface AppRoot {}
}

declare global {


  interface HTMLAppAuthElement extends Components.AppAuth, HTMLStencilElement {}
  var HTMLAppAuthElement: {
    prototype: HTMLAppAuthElement;
    new (): HTMLAppAuthElement;
  };

  interface HTMLAppAuthPageElement extends Components.AppAuthPage, HTMLStencilElement {}
  var HTMLAppAuthPageElement: {
    prototype: HTMLAppAuthPageElement;
    new (): HTMLAppAuthPageElement;
  };

  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-auth': HTMLAppAuthElement;
    'app-auth-page': HTMLAppAuthPageElement;
    'app-header': HTMLAppHeaderElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface AppAuth {}
  interface AppAuthPage {}
  interface AppHeader {}
  interface AppRoot {}

  interface IntrinsicElements {
    'app-auth': AppAuth;
    'app-auth-page': AppAuthPage;
    'app-header': AppHeader;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-auth': LocalJSX.AppAuth & JSXBase.HTMLAttributes<HTMLAppAuthElement>;
      'app-auth-page': LocalJSX.AppAuthPage & JSXBase.HTMLAttributes<HTMLAppAuthPageElement>;
      'app-header': LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
    }
  }
}


